apiVersion: v1
kind: Service
metadata:
  name: smoke-echo
  labels:
    app.kubernetes.io/name: smoke-echo
    app.kubernetes.io/part-of: gitops-smoke
    platformone.io/owner: platform-engineering
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: smoke-echo
  ports:
    - name: http
      port: 80
      targetPort: 80
